export enum EVENTS {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  INPUT_FOCUS = 'INPUT_FOCUS',
  INPUT_BLUR = 'INPUT_BLUR',
  INPUT_ERROR = 'INPUT_ERROR',
  INPUT_OK = 'INPUT_OK',
  FORM_SUBMIT = 'FORM_SUBMIT',
  FORM_VALID = 'FORM_VALID',
  SEARCH_UPDATE = 'SEARCH_UPDATE',
  PAGE_CLICK = 'PAGE_CLICK',
}
